title: Settings
data:
  site_name: 'Gabor''s Bloooooooooooooog'
  personality: formal
  show_signup: false
  social:
    -
      name: Twitter
      url: 'https://twitter.com/gabikasb'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/gabikasb'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:gabor@gaborgyure.com'
      icon: site/social-icons/email.svg
